version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://user_app:123456789987654321@db:5432/user_app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_app
      POSTGRES_PASSWORD: 123456789987654321
      POSTGRES_DB: user_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: