
version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - "3001:3001"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://user_app:123456789987654321@db:5432/user_app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_app
      POSTGRES_PASSWORD: 123456789987654321
      POSTGRES_DB: user_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx_server

    ports:
      - "80:80"
    volumes:
      - ../../media:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - api

volumes:
  postgres_data:
