version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - "3002:3002"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://user_app:123456789987654321@db:5432/user_app
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_app
      POSTGRES_PASSWORD: 123456789987654321
      POSTGRES_DB: user_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    command: celery -A web worker --loglevel=info
    volumes:
      - ../../:/app
    depends_on:
      - api
      - redis
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://user_app:123456789987654321@db:5432/user_app
      - CELERY_BROKER_URL=redis://redis:6379/0

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "85:85"
    volumes:
      - ../../media:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  postgres_data:
