# Generated by Django 4.2 on 2025-05-27 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0004_banusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('logoImage', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('licenceImage', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل املاک')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('bio', models.TextField(blank=True, null=True)),
                ('timeWork', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('rejected', 'رد شده')], default='inactive', max_length=20)),
                ('cities', models.ManyToManyField(blank=True, related_name='agencies', to='core.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='استان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agency.agency')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='agency.agency')),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
            },
        ),
    ]
