# Generated by Django 4.2 on 2025-05-28 08:02

import apps.agency.models.validation.agency_valid
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=255, validators=[apps.agency.models.validation.agency_valid.validate_name]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
    ]
