# Generated by Django 4.2 on 2025-05-28 08:38

import apps.agency.models.validation.agency_valid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0002_alter_agency_bannerimage_alter_agency_licenceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.CreateModel(
            name='RequestCollaborationAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('role', models.CharField(choices=[('manager', 'مدیر'), ('consultant', 'مشاور'), ('admin', 'ادمین')], default='consultant', max_length=20, verbose_name='نقش درخواستی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('request_message', models.TextField(blank=True, null=True, verbose_name='پیام درخواست')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='پاسخ آژانس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='agency.agency', verbose_name='آژانس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست دهنده')),
            ],
            options={
                'verbose_name': 'درخواست همکاری با آژانس',
                'verbose_name_plural': 'درخواست\u200cهای همکاری با آژانس',
                'db_table': 'agency_collaboration_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requestcollaborationagency',
            index=models.Index(fields=['agency', 'user'], name='agency_coll_agency__0cd950_idx'),
        ),
        migrations.AddIndex(
            model_name='requestcollaborationagency',
            index=models.Index(fields=['status'], name='agency_coll_status_05cec4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestcollaborationagency',
            index=models.Index(fields=['isActive'], name='agency_coll_isActiv_f89432_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestcollaborationagency',
            unique_together={('agency', 'user')},
        ),
    ]
