# Generated by Django 4.2 on 2025-05-29 08:28

import apps.agency.models.validation.agency_valid
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_agency_bannerimage_alter_agency_licenceimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcollaborationagency',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consultant',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعال'),
        ),
        migrations.AddField(
            model_name='manager',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعال'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
    ]
