# Generated by Django 4.2 on 2025-05-31 07:47

import apps.agency.models.validation.agency_valid
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_requestcollaborationagency_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='agency',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.CreateModel(
            name='RejectedAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency', verbose_name='اژآنس')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
