# Generated by Django 4.2 on 2025-05-31 07:52

import apps.agency.models.validation.agency_valid
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_rename_created_at_agency_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcollaborationagency',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='requestcollaborationagency',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='requestcollaborationagency',
            old_name='updated_at',
            new_name='updateAt',
        ),
        migrations.AlterField(
            model_name='agency',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
    ]
