# Generated by Django 4.2 on 2025-06-01 05:34

import apps.agency.models.validation.agency_valid
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_agency_bannerimage_alter_agency_licenceimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcollaborationagency',
            name='updateAt',
        ),
        migrations.AddField(
            model_name='requestcollaborationagency',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, validators=[apps.agency.models.validation.agency_valid.profile_image_validator]),
        ),
        migrations.AlterField(
            model_name='requestcollaborationagency',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
