# Generated by Django 4.2 on 2025-05-14 19:46

import apps.user.models.user_model
import apps.user.models.validation.user_validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ایدی')),
                ('mobileNumber', models.CharField(max_length=11, unique=True, validators=[apps.user.models.validation.user_validation.ValidMobileNumber], verbose_name='شماره موبایل')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کوچیک')),
                ('lastName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فامیلی')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('countryCode', models.CharField(blank=True, max_length=5, null=True, verbose_name='کد کشور')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('femail', 'زن'), ('other', 'سایر')], default='male', max_length=10, null=True, verbose_name='جنسیت')),
                ('birthday', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد')),
                ('password', models.CharField(blank=True, max_length=36, null=True, validators=[apps.user.models.user_model.validate_password], verbose_name='رمز عبور')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='کاربر ادمین پلاس')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'user',
            },
            bases=(models.Model, apps.user.models.validation.user_validation.CleanFieldsMixin),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('test_field', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ایدی')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=20, verbose_name='نامک نقش')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.currency', verbose_name='نوع ارز')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'user_wallet',
            },
        ),
        migrations.CreateModel(
            name='UserSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isBan', models.BooleanField(default=False, verbose_name='وضعیت بلاک')),
                ('isVerfied', models.BooleanField(default=False)),
                ('isInfoFiled', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('activeCode', models.CharField(max_length=5, verbose_name='کد تایید')),
                ('expireDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'user_secret',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLogin', models.DateTimeField(auto_now_add=True, verbose_name='زمان اخرین ورود')),
                ('ip', models.CharField(max_length=15, verbose_name='ای پی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.roleuser', verbose_name='نقش کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
