# Generated by Django 4.2 on 2025-05-15 09:50

import apps.user.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[apps.user.models.user_model.validate_password], verbose_name='رمز عبور'),
        ),
    ]
