# Generated by Django 4.2 on 2025-05-21 12:34

import apps.user.models.user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='آدرس IP')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بلاک')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل بلاک')),
                ('requests_count', models.PositiveIntegerField(default=1, verbose_name='تعداد درخواست\u200cها')),
                ('time_frame_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه زمانی (ثانیه)')),
                ('max_requests', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر درخواست مجاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'IP بلاک شده',
                'verbose_name_plural': 'IPهای بلاک شده',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کاربر ادمین '),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[apps.user.models.user_model.validate_password], verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.currency', verbose_name='نوع ارز'),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='کد خطا')),
                ('endpoint', models.CharField(max_length=255, verbose_name='آدرس اندپوینت')),
                ('message', models.TextField(blank=True, null=True, verbose_name='تکست خطا')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات')),
                ('ipAddress', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='user_reques_ip_addr_a1d2d3_idx'),
        ),
    ]
