# Generated by Django 4.2 on 2025-05-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blockedip_requestlog_rename_userid_wallet_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUseage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام پروژه')),
                ('result', models.CharField(blank=True, max_length=100, verbose_name='نتیجه ماندگاری')),
                ('status', models.CharField(choices=[('entered', 'ورود'), ('active', 'داخل سایت'), ('exited', 'خروج')], max_length=10, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
