# Generated by Django 4.2 on 2025-05-26 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useruseage'),
    ]

    operations = [
        migrations.CreateModel(
            name='banUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('banSubject', models.CharField(choices=[('agency', 'اژانس'), ('advertisement', 'اگهی'), ('manager', 'مدیر')], max_length=100, verbose_name='نوع رد')),
                ('isCheck', models.BooleanField(default=False, verbose_name='چک شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
