# Generated by Django 4.2 on 2025-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
