# Generated by Django 4.2 on 2025-05-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_wallet_updateat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='updateAt',
        ),
    ]
