# Generated by Django 4.2 on 2025-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_wallet_updateat'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
