# Generated by Django 4.2 on 2025-05-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_wallet_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='userId',
            new_name='user',
        ),
    ]
