# Generated by Django 4.2 on 2025-05-17 16:02

import apps.user.models.loguser_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_userid_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='کد خطا')),
                ('endpoint', models.CharField(max_length=255, verbose_name='آدرس اندپوینت')),
                ('message', models.TextField(blank=True, null=True, verbose_name='تکست خطا')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBan', models.BooleanField(default=False, verbose_name='بلاک شده')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ساخته شده')),
                ('ipAddress', models.CharField(max_length=1000, verbose_name='آدرس IP')),
                ('expireSince', models.DateTimeField(default=apps.user.models.loguser_model.default_expire_time, verbose_name='تاریخ انقضا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'black_list',
            },
        ),
    ]
