# Generated by Django 4.2 on 2025-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userlog_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس IP'),
        ),
    ]
