# Generated by Django 4.2 on 2025-05-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userlog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
