# Generated by Django 4.2 on 2025-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='آدرس IP')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بلاک')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل بلاک')),
                ('requests_count', models.PositiveIntegerField(default=1, verbose_name='تعداد درخواست\u200cها')),
                ('time_frame_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه زمانی (ثانیه)')),
                ('max_requests', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر درخواست مجاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'IP بلاک شده',
                'verbose_name_plural': 'IPهای بلاک شده',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='user_reques_ip_addr_a1d2d3_idx'),
        ),
    ]
