# Generated by Django 4.2 on 2025-06-07 11:37

import apps.estate.models.advertisement
import apps.estate.models.utilities
import apps.user.models.validation.user_validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.BigIntegerField(verbose_name='قیمت آگهی')),
                ('viewCount', models.BigIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('expired_at', models.DateTimeField(default=apps.estate.models.advertisement.get_expiry_date, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
            },
            bases=(models.Model, apps.user.models.validation.user_validation.CleanFieldsMixin),
        ),
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع آگهی',
                'verbose_name_plural': 'انواع آگهی',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('typeGroup', models.CharField(choices=[('additionalFilters', 'ویژگی اضافی'), ('amenities', 'امکانات'), ('mainFeature', 'ویژگی اصلی')], max_length=50, verbose_name='نوع دسته بندی')),
                ('typeValue', models.CharField(choices=[('number', 'عدد'), ('string', 'رشته'), ('bool', 'منطقی')], max_length=50, verbose_name='نوع داده')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع گزارش')),
            ],
            options={
                'verbose_name': 'نوع گزارش',
                'verbose_name_plural': 'انواع گزارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='StatusAdvertisemen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'وضعیت آگهی',
                'verbose_name_plural': 'وضعیت\u200cهای آگهی',
            },
        ),
        migrations.CreateModel(
            name='TypeFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع ویژگی',
                'verbose_name_plural': 'انواع ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TypePremium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع خاص',
                'verbose_name_plural': 'پرمیوم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SecretAdvertisement',
            fields=[
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estate.advertisement', verbose_name='اگهی')),
                ('isRenewal', models.BooleanField(default=False, verbose_name='تمدید')),
                ('isInfoCompleted', models.BooleanField(default=False, verbose_name='تکمیل اطلاعات')),
                ('isFlagged', models.BooleanField(default=False, verbose_name='وضعیت اگهی مشکوک')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('grade', models.CharField(choices=[('normal', 'عادی'), ('medium', 'متوسط'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='سطح اهمیت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('error_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خطا')),
                ('is_handled', models.BooleanField(default=False, verbose_name='بررسی شده')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estate.reporttype', verbose_name='نوع گزارش')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('advertisement_types', models.ManyToManyField(related_name='property_types', to='estate.advertisementtype', verbose_name='نوع آگهی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='estate.propertytype', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'انواع ملک',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='estate.feature', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='propertyTypes',
            field=models.ManyToManyField(related_name='features', to='estate.propertytype', verbose_name='نوع ملک'),
        ),
        migrations.AddField(
            model_name='feature',
            name='typeFeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='estate.typefeature', verbose_name='نوع ویژگی'),
        ),
        migrations.CreateModel(
            name='AdvertisementGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('original_image', models.ImageField(upload_to=apps.estate.models.utilities.upload_to_original, verbose_name='تصویر اصلی')),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.estate.models.utilities.upload_to_thumbnail, verbose_name='تصویر بند انگشتی')),
                ('small', models.ImageField(blank=True, upload_to=apps.estate.models.utilities.upload_to_small, verbose_name='تصویر کوچک')),
                ('medium', models.ImageField(blank=True, upload_to=apps.estate.models.utilities.upload_to_medium, verbose_name='تصویر متوسط')),
                ('large', models.ImageField(blank=True, upload_to=apps.estate.models.utilities.upload_to_large, verbose_name='تصویر بزرگ')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='estate.advertisement', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'گالری آگهی',
                'verbose_name_plural': 'گالری\u200cهای آگهی',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='estate.advertisementtype', verbose_name='نوع آگهی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='premiumtypes',
            field=models.ManyToManyField(blank=True, to='estate.typepremium', verbose_name='نوع پرمیوم'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='propertyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='estate.propertytype', verbose_name='نوع ملک'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate.statusadvertisemen', verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='کاربر آگهی\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='userConfirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_advertisements', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تأیید\u200cکننده'),
        ),
        migrations.CreateModel(
            name='AdvertisementLocation',
            fields=[
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estate.advertisement', verbose_name='اگهی')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='محله')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='شهر')),
            ],
        ),
    ]
