# Generated by Django 4.2 on 2025-06-08 08:35

import apps.estate.models.gallery
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisementgallery',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='large',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='small',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='advertisementgallery',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='عکس شاخص'),
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.estate.models.gallery.upload_large, verbose_name='تصویر بزرگ'),
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='medium_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.estate.models.gallery.upload_medium, verbose_name='تصویر متوسط'),
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='org_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.estate.models.gallery.upload_original, verbose_name='تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.estate.models.gallery.upload_small, verbose_name='تصویر کوچک'),
        ),
        migrations.AddField(
            model_name='advertisementgallery',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.estate.models.gallery.upload_thumbnail, verbose_name='تصویر بند انگشتی'),
        ),
        migrations.AlterField(
            model_name='advertisementgallery',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_gallery', to='estate.advertisement', verbose_name='آگهی'),
        ),
    ]
